--[[

        1.lua
        exported by excel2lua.py
        from file:1.xlsx

--]]

return {
  [1] = {
   id = 1,
   cStatement = '声文跟读：参照动画截图对话框中的句子发音，进行跟读练习。',
   statement = 'Follow to read',
   voice = 'Follow to read.mp3',
   tableIds = 14,
   textIds = {1,2,3,4,5,6,7,8,9,10,11,12,13,14},
  },
  [2] = {
   id = 2,
   cStatement = '声文跟读：参照动画截图对话框中的句子发音，进行跟读练习。',
   statement = 'Follow to read',
   voice = 'Follow to read.mp3',
   tableIds = -1,
   textIds = {},
  },
  [3] = {
   id = 3,
   cStatement = '声文跟读：参照动画截图对话框中的句子发音，进行跟读练习。',
   statement = 'Follow to read',
   voice = 'Follow to read.mp3',
   tableIds = -1,
   textIds = {},
  },
  [4] = {
   id = 4,
   cStatement = '声文跟读：参照动画截图对话框中的句子发音，进行跟读练习。',
   statement = 'Follow to read',
   voice = 'Follow to read.mp3',
   tableIds = -1,
   textIds = {},
  },
  [5] = {
   id = 5,
   cStatement = '声文跟读：参照动画截图对话框中的句子发音，进行跟读练习。',
   statement = 'Follow to read',
   voice = 'Follow to read.mp3',
   tableIds = -1,
   textIds = {},
  },
  [6] = {
   id = 6,
   cStatement = '声文跟读：参照动画截图对话框中的句子发音，进行跟读练习。',
   statement = 'Follow to read',
   voice = 'Follow to read.mp3',
   tableIds = -1,
   textIds = {},
  },
  [7] = {
   id = 7,
   cStatement = '声文跟读：参照动画截图对话框中的句子发音，进行跟读练习。',
   statement = 'Follow to read',
   voice = 'Follow to read.mp3',
   tableIds = -1,
   textIds = {},
  },
  [8] = {
   id = 8,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [9] = {
   id = 9,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [10] = {
   id = 10,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [11] = {
   id = 11,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [12] = {
   id = 12,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [13] = {
   id = 13,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [14] = {
   id = 14,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [15] = {
   id = 15,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [16] = {
   id = 16,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [17] = {
   id = 17,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [18] = {
   id = 18,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [19] = {
   id = 19,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [20] = {
   id = 20,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [21] = {
   id = 21,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
  [22] = {
   id = 22,
   cStatement = '',
   statement = '',
   voice = '',
   tableIds = -1,
   textIds = {},
  },
}
