--[[

        10.lua
        exported by excel2lua.py
        from file:10.xlsx

--]]

return {
  [1] = {
   id = 1,
   word = 'hello',
   cword = '打招呼',
   icon1 = 'hello-1.jpg',
   icon2 = 'hello-2.jpg',
   voice = 'hello.mp3',
  },
  [2] = {
   id = 2,
   word = 'welcome',
   cword = '欢迎',
   icon1 = 'welcome-1.jpg',
   icon2 = 'welcome-2.jpg',
   voice = 'welcome.mp3',
  },
  [3] = {
   id = 3,
   word = 'spaceship',
   cword = '太空飞船',
   icon1 = 'spaceship-1.jpg',
   icon2 = 'spaceship-2.jpg',
   voice = 'spaceship.mp3',
  },
  [4] = {
   id = 4,
   word = 'Dr.',
   cword = '博士',
   icon1 = 'Dr.-1.jpg',
   icon2 = 'Dr.-2.jpg',
   voice = 'doctor.mp3',
  },
  [5] = {
   id = 5,
   word = 'name',
   cword = '名字',
   icon1 = 'name-1.jpg',
   icon2 = 'name-2.jpg',
   voice = 'name.mp3',
  },
  [6] = {
   id = 6,
   word = 'friend',
   cword = '朋友',
   icon1 = 'friend-1.jpg',
   icon2 = 'friend-2.jpg',
   voice = 'friend.mp3',
  },
  [7] = {
   id = 7,
   word = 'nice',
   cword = '美好的',
   icon1 = 'nice-1.jpg',
   icon2 = 'nice-2.jpg',
   voice = 'nice.mp3',
  },
  [8] = {
   id = 8,
   word = 'meet',
   cword = '相识',
   icon1 = 'meet-1.jpg',
   icon2 = 'meet-2.jpg',
   voice = 'meet.mp3',
  },
  [9] = {
   id = 9,
   word = 'who',
   cword = '谁',
   icon1 = 'who-1.jpg',
   icon2 = 'who-2.jpg',
   voice = 'who.mp3',
  },
  [10] = {
   id = 10,
   word = 'there',
   cword = '那儿',
   icon1 = 'there-1.jpg',
   icon2 = 'there-2.jpg',
   voice = 'there.mp3',
  },
  [11] = {
   id = 11,
   word = 'your',
   cword = '你（们）的',
   icon1 = 'your-1.jpg',
   icon2 = 'your-2.jpg',
   voice = 'your.mp3',
  },
  [12] = {
   id = 12,
   word = 'bag',
   cword = '包',
   icon1 = 'bag-1.jpg',
   icon2 = 'bag-2.jpg',
   voice = 'bag.mp3',
  },
  [13] = {
   id = 13,
   word = 'open',
   cword = '打开',
   icon1 = 'open-1.jpg',
   icon2 = 'open-2.jpg',
   voice = 'open.mp3',
  },
  [14] = {
   id = 14,
   word = 'ruler',
   cword = '尺子',
   icon1 = 'ruler-1.jpg',
   icon2 = 'ruler-2.jpg',
   voice = 'ruler.mp3',
  },
  [15] = {
   id = 15,
   word = 'pencil',
   cword = '铅笔',
   icon1 = 'pencil-1.jpg',
   icon2 = 'pencil-2.jpg',
   voice = 'pencil.mp3',
  },
  [16] = {
   id = 16,
   word = 'eraser',
   cword = '橡皮',
   icon1 = 'eraser-1.jpg',
   icon2 = 'eraser-2.jpg',
   voice = 'eraser.mp3',
  },
  [17] = {
   id = 17,
   word = 'crayon',
   cword = '蜡笔',
   icon1 = 'crayon-1.jpg',
   icon2 = 'crayon-2.jpg',
   voice = 'crayon.mp3',
  },
  [18] = {
   id = 18,
   word = 'pen',
   cword = '钢笔',
   icon1 = 'pen-1.jpg',
   icon2 = 'pen-2.jpg',
   voice = 'pen.mp3',
  },
  [19] = {
   id = 19,
   word = 'pencil box  ',
   cword = '铅笔盒',
   icon1 = 'pencil box-1.jpg ',
   icon2 = 'pencil box-2.jpg',
   voice = 'pencil box.mp3 ',
  },
  [20] = {
   id = 20,
   word = 'book',
   cword = '书',
   icon1 = 'book-1.jpg',
   icon2 = 'book-2.jpg',
   voice = 'book.mp3',
  },
  [21] = {
   id = 21,
   word = 'touch',
   cword = '触碰',
   icon1 = 'touch-1.jpg',
   icon2 = 'touch-2.jpg',
   voice = 'touch.mp3',
  },
  [22] = {
   id = 22,
   word = 'badge',
   cword = '徽章',
   icon1 = 'badge-1.jpg',
   icon2 = 'badge-2.jpg',
   voice = 'badge.mp3',
  },
  [23] = {
   id = 23,
   word = 'cool',
   cword = '酷的;绝妙的',
   icon1 = 'cool-1.jpg',
   icon2 = 'cool-2.jpg',
   voice = 'cool.mp3',
  },
  [24] = {
   id = 24,
   word = 'sword',
   cword = '剑',
   icon1 = 'sword-1.jpg',
   icon2 = 'sword-2.jpg',
   voice = 'sword.mp3',
  },
  [25] = {
   id = 25,
   word = 'gun',
   cword = '枪',
   icon1 = 'gun-1.jpg',
   icon2 = 'gun-2.jpg',
   voice = 'gun.mp3',
  },
  [26] = {
   id = 26,
   word = 'thank',
   cword = '谢谢',
   icon1 = 'thank-1.jpg',
   icon2 = 'thank-2.jpg',
   voice = 'thank.mp3',
  },
  [27] = {
   id = 27,
   word = 'no',
   cword = '不',
   icon1 = 'no-1.jpg',
   icon2 = 'no-2.jpg',
   voice = 'no.mp3',
  },
  [28] = {
   id = 28,
   word = 'morning',
   cword = '早晨',
   icon1 = 'morning-1.jpg',
   icon2 = 'morning-2.jpg',
   voice = 'morning.mp3',
  },
  [29] = {
   id = 29,
   word = 'this',
   cword = '这个',
   icon1 = 'this-1.jpg',
   icon2 = 'this-2.jpg',
   voice = 'this.mp3',
  },
  [30] = {
   id = 30,
   word = 'too',
   cword = '也；同样',
   icon1 = 'too-1.jpg',
   icon2 = 'too-2.jpg',
   voice = 'too.mp3',
  },
  [31] = {
   id = 31,
   word = 'kid',
   cword = '小孩',
   icon1 = 'kid-1.jpg',
   icon2 = 'kid-2.jpg',
   voice = 'kid.mp3',
  },
  [32] = {
   id = 32,
   word = 'fine',
   cword = '好的',
   icon1 = 'fine-1.jpg',
   icon2 = 'fine-2.jpg',
   voice = 'fine.mp3',
  },
  [33] = {
   id = 33,
   word = 'so',
   cword = '这么',
   icon1 = 'so-1.jpg',
   icon2 = 'so-2.jpg',
   voice = 'so.mp3',
  },
  [34] = {
   id = 34,
   word = 'many',
   cword = '许多',
   icon1 = 'many-1.jpg',
   icon2 = 'many-2.jpg',
   voice = 'many.mp3',
  },
  [35] = {
   id = 35,
   word = 'planet',
   cword = '星球',
   icon1 = 'planet-1.jpg',
   icon2 = 'planet-2.jpg',
   voice = 'planet.mp3',
  },
  [36] = {
   id = 36,
   word = 'red',
   cword = '红色（的）',
   icon1 = 'red-1.jpg',
   icon2 = 'red-2.jpg',
   voice = 'red.mp3',
  },
  [37] = {
   id = 37,
   word = 'white',
   cword = '白色（的）',
   icon1 = 'white-1.jpg',
   icon2 = 'white-2.jpg',
   voice = 'white.mp3',
  },
  [38] = {
   id = 38,
   word = 'yellow',
   cword = '黄色（的）',
   icon1 = 'yellow-1.jpg',
   icon2 = 'yellow-2.jpg',
   voice = 'yellow.mp3',
  },
  [39] = {
   id = 39,
   word = 'green',
   cword = '绿色（的）',
   icon1 = 'green-1.jpg',
   icon2 = 'green-2.jpg',
   voice = 'green.mp3',
  },
  [40] = {
   id = 40,
   word = 'brown',
   cword = '棕色（的）',
   icon1 = 'brown-1.jpg',
   icon2 = 'brown-2.jpg',
   voice = 'brown.mp3',
  },
  [41] = {
   id = 41,
   word = 'orange',
   cword = '橙色（的）',
   icon1 = 'orange-1.jpg',
   icon2 = 'orange-2.jpg',
   voice = 'orange.mp3',
  },
  [42] = {
   id = 42,
   word = 'blue',
   cword = '蓝色（的）',
   icon1 = 'blue-1.jpg',
   icon2 = 'blue-2.jpg',
   voice = 'blue.mp3',
  },
  [43] = {
   id = 43,
   word = 'one',
   cword = '那一个',
   icon1 = 'one-1.jpg',
   icon2 = 'one-2.jpg',
   voice = 'one.mp3',
  },
  [44] = {
   id = 44,
   word = 'home',
   cword = '家',
   icon1 = 'home-1.jpg',
   icon2 = 'home-2.jpg',
   voice = 'home.mp3',
  },
  [45] = {
   id = 45,
   word = 'miss',
   cword = '想念；丢失',
   icon1 = 'miss-1.jpg',
   icon2 = 'miss-2.jpg',
   voice = 'miss.mp3',
  },
  [46] = {
   id = 46,
   word = 'upset',
   cword = '沮丧的',
   icon1 = 'upset-1.jpg',
   icon2 = 'upset-2.jpg',
   voice = 'upset.mp3',
  },
  [47] = {
   id = 47,
   word = 'everybody',
   cword = '每人',
   icon1 = 'everybody-1.jpg',
   icon2 = 'everybody-2.jpg',
   voice = 'everybody.mp3',
  },
  [48] = {
   id = 48,
   word = 'black',
   cword = '黑色（的）',
   icon1 = 'black-1.jpg',
   icon2 = 'black-2.jpg',
   voice = 'black.mp3',
  },
  [49] = {
   id = 49,
   word = 'button',
   cword = '按钮',
   icon1 = 'button-1.jpg',
   icon2 = 'button-2.jpg',
   voice = 'button.mp3',
  },
  [50] = {
   id = 50,
   word = 'target',
   cword = '目标',
   icon1 = 'target-1.jpg',
   icon2 = 'target-2.jpg',
   voice = 'target.mp3',
  },
  [51] = {
   id = 51,
   word = 'push',
   cword = '推',
   icon1 = 'push-1.jpg',
   icon2 = 'push-2.jpg',
   voice = 'push.mp3',
  },
  [52] = {
   id = 52,
   word = 'full',
   cword = '全部的',
   icon1 = 'full-1.jpg',
   icon2 = 'full-2.jpg',
   voice = 'full.mp3',
  },
  [53] = {
   id = 53,
   word = 'speed',
   cword = '速度',
   icon1 = 'speed-1.jpg',
   icon2 = 'speed-2.jpg',
   voice = 'speed.mp3',
  },
  [54] = {
   id = 54,
   word = 'ahead',
   cword = '向前',
   icon1 = 'ahead-1.jpg',
   icon2 = 'ahead-2.jpg',
   voice = 'ahead.mp3',
  },
  [55] = {
   id = 55,
   word = 'stand up ',
   cword = '站起来',
   icon1 = 'stand up-1.jpg',
   icon2 = 'stand up-2.jpg',
   voice = 'stand up.mp3',
  },
  [56] = {
   id = 56,
   word = 'sit down',
   cword = '坐下去',
   icon1 = 'sit down-1.jpg',
   icon2 = 'sit down-2.jpg',
   voice = 'sit down.mp3',
  },
  [57] = {
   id = 57,
   word = 'OK',
   cword = '好的',
   icon1 = 'OK-1.jpg',
   icon2 = 'OK-2.jpg',
   voice = 'OK.mp3',
  },
  [58] = {
   id = 58,
   word = 'mum',
   cword = '妈妈',
   icon1 = 'mum-1.jpg',
   icon2 = 'mum-2.jpg',
   voice = 'mum.mp3',
  },
}
