--[[

        10.lua
        exported by excel2lua.py
        from file:10.xlsx

--]]

return {
  [1] = {
   id = 1,
   word = 'hello',
   cword = '打招呼',
   icon = 'hello.jpg',
   voice = 'hello.mp3',
  },
  [2] = {
   id = 2,
   word = 'welcome',
   cword = '欢迎',
   icon = 'welcome.jpg',
   voice = 'welcome.mp3',
  },
  [3] = {
   id = 3,
   word = 'spaceship',
   cword = '太空飞船',
   icon = 'spaceship.jpg',
   voice = 'spaceship.mp3',
  },
  [4] = {
   id = 4,
   word = 'Dr.',
   cword = '博士',
   icon = 'Dr..jpg',
   voice = 'Dr..mp3',
  },
  [5] = {
   id = 5,
   word = 'name',
   cword = '名字',
   icon = 'name.jpg',
   voice = 'name.mp3',
  },
  [6] = {
   id = 6,
   word = 'friend',
   cword = '朋友',
   icon = 'friend.jpg',
   voice = 'friend.mp3',
  },
  [7] = {
   id = 7,
   word = 'nice',
   cword = '美好的',
   icon = 'nice.jpg',
   voice = 'nice.mp3',
  },
  [8] = {
   id = 8,
   word = 'meet',
   cword = '相识',
   icon = 'meet.jpg',
   voice = 'meet.mp3',
  },
  [9] = {
   id = 9,
   word = 'who',
   cword = '谁',
   icon = 'who.jpg',
   voice = 'who.mp3',
  },
  [10] = {
   id = 10,
   word = 'there',
   cword = '那儿',
   icon = 'there.jpg',
   voice = 'there.mp3',
  },
  [11] = {
   id = 11,
   word = 'your',
   cword = '你（们）的',
   icon = 'your.jpg',
   voice = 'your.mp3',
  },
  [12] = {
   id = 12,
   word = 'bag',
   cword = '包',
   icon = 'bag.jpg',
   voice = 'bag.mp3',
  },
  [13] = {
   id = 13,
   word = 'open',
   cword = '打开',
   icon = 'open.jpg',
   voice = 'open.mp3',
  },
  [14] = {
   id = 14,
   word = 'ruler',
   cword = '尺子',
   icon = 'ruler.jpg',
   voice = 'ruler.mp3',
  },
  [15] = {
   id = 15,
   word = 'pencil',
   cword = '铅笔',
   icon = 'pencil.jpg',
   voice = 'pencil.mp3',
  },
  [16] = {
   id = 16,
   word = 'eraser',
   cword = '橡皮',
   icon = 'eraser.jpg',
   voice = 'eraser.mp3',
  },
  [17] = {
   id = 17,
   word = 'crayon',
   cword = '蜡笔',
   icon = 'crayon.jpg',
   voice = 'crayon.mp3',
  },
  [18] = {
   id = 18,
   word = 'pen',
   cword = '钢笔',
   icon = 'pen.jpg',
   voice = 'pen.mp3',
  },
  [19] = {
   id = 19,
   word = 'pencil box  ',
   cword = '铅笔盒',
   icon = 'pencil box.jpg ',
   voice = 'pencil box.mp3 ',
  },
  [20] = {
   id = 20,
   word = 'book',
   cword = '书',
   icon = 'book.jpg',
   voice = 'book.mp3',
  },
  [21] = {
   id = 21,
   word = 'touch',
   cword = '触碰',
   icon = 'touch.jpg',
   voice = 'touch.mp3',
  },
  [22] = {
   id = 22,
   word = 'badge',
   cword = '徽章',
   icon = 'badge.jpg',
   voice = 'badge.mp3',
  },
  [23] = {
   id = 23,
   word = 'cool',
   cword = '酷的;绝妙的',
   icon = 'cool.jpg',
   voice = 'cool.mp3',
  },
  [24] = {
   id = 24,
   word = 'sword',
   cword = '剑',
   icon = 'sword.jpg',
   voice = 'sword.mp3',
  },
  [25] = {
   id = 25,
   word = 'gun',
   cword = '枪',
   icon = 'gun.jpg',
   voice = 'gun.mp3',
  },
  [26] = {
   id = 26,
   word = 'thank',
   cword = '谢谢',
   icon = 'thank.jpg',
   voice = 'thank.mp3',
  },
  [27] = {
   id = 27,
   word = 'no',
   cword = '不',
   icon = 'no.jpg',
   voice = 'no.mp3',
  },
}
