--[[

        12.lua
        exported by excel2lua.py
        from file:12.xlsx

--]]

return {
  [1] = {
   id = 1,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Mike.',
   voice = '3AU1D1S1.mp3',
   deleUserId = 1,
   confuse = {'Hello, I\'m Mike.','Hello, you are Mike.','Goodbye, I\'m Mike.'},
   confuseVoice = {'3AU1D1S1.mp3','3AU1D1S1M1.mp3','3AU1D1S1M2.mp3'} ,
  },
  [2] = {
   id = 2,
   headTable = 'head',
   headId = 2,
   text = 'Hi, I\'m Wu Yifan.',
   voice = '3AU1D1S2.mp3',
   deleUserId = 2,
   confuse = {'Hi, I\'m Wu Yifan.','Goodbye, I\'m Wu Yifan. ','Hi, you are Wu Yifan.'},
   confuseVoice = {'3AU1D1S2.mp3','3AU1D1S2M1.mp3','3AU1D1S2M2.mp3'} ,
  },
  [3] = {
   id = 3,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Mike.',
   voice = '3AU1D1S1.mp3',
   deleUserId = 1,
   confuse = {'Hello,','I\'m','Mike.'}  ,
   confuseVoice = {'3AU1D1S1P1.mp3','3AU1D1S1P2.mp3','3AU1D1S1P3.mp3'} ,
  },
  [4] = {
   id = 4,
   headTable = 'head',
   headId = 2,
   text = 'Hi, I\'m Wu Yifan.',
   voice = '3AU1D1S2.mp3',
   deleUserId = 2,
   confuse = {'Hi,',' I\'m','Wu Yifan.'},
   confuseVoice = {'3AU1D1S2P1.mp3','3AU1D1S2P2.mp3','3AU1D1S2P3.mp3'} ,
  },
  [5] = {
   id = 5,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Chen Jie.',
   voice = '3AU1D2S1.mp3',
   deleUserId = 1,
   confuse = {'Hello, I\'m Chen Jie.','Hello, my Chen Jie..','Goodbye, I\'m Chen Jie.'},
   confuseVoice = {'3AU1D2S1.mp3','3AU1D2S1M1.mp3','3AU1D2S1M2.mp3'} ,
  },
  [6] = {
   id = 6,
   headTable = 'head',
   headId = 1,
   text = 'What\'s your name?',
   voice = '3AU1D2S2.mp3',
   deleUserId = 1,
   confuse = {'What\'s your name?','What\'s you name?','How is your name?'},
   confuseVoice = {'3AU1D2S2.mp3','3AU1D2S2M1.mp3','3AU1D2S2M2.mp3'} ,
  },
  [7] = {
   id = 7,
   headTable = 'head',
   headId = 2,
   text = 'My name\'s Sarah.',
   voice = '3AU1D2S3.mp3',
   deleUserId = 2,
   confuse = {'My name\'s Sarah.','Her name\'s Sarah.','My name are Sarah.'},
   confuseVoice = {'3AU1D2S3.mp3','3AU1D2S3M1.mp3','3AU1D2S3M2.mp3'} ,
  },
  [8] = {
   id = 8,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Chen Jie.',
   voice = '3AU1D2S1.mp3',
   deleUserId = 1,
   confuse = {'Hello,','I\'m','Chen Jie.'} ,
   confuseVoice = {'3AU1D2S1P1.mp3','3AU1D2S1P2.mp3','3AU1D2S1P3.mp3'} ,
  },
  [9] = {
   id = 9,
   headTable = 'head',
   headId = 1,
   text = 'What\'s your name?',
   voice = '3AU1D2S2.mp3',
   deleUserId = 1,
   confuse = {'What\'s',' your','name?'},
   confuseVoice = {'3AU1D2S2P1.mp3','3AU1D2S2P2.mp3','3AU1D2S2P3.mp3'} ,
  },
  [10] = {
   id = 10,
   headTable = 'head',
   headId = 2,
   text = 'My name\'s Sarah.',
   voice = '3AU1D2S3.mp3',
   deleUserId = 2,
   confuse = {'My',' name\'s','Sarah.'},
   confuseVoice = {'3AU1D2S3P1.mp3','3AU1D2S3P2.mp3','3AU1D2S3P3.mp3'} ,
  },
  [11] = {
   id = 11,
   headTable = 'head',
   headId = 1,
   text = 'Bye, Miss White!',
   voice = '3AU1D3S1.mp3',
   deleUserId = 1,
   confuse = {'Bye, Miss White!','Hello, Miss White!','Have fun, Miss White!'},
   confuseVoice = {'3AU1D3S1.mp3','3AU1D3S1M1.mp3','3AU1D3S1M2.mp3'} ,
  },
  [12] = {
   id = 12,
   headTable = 'head',
   headId = 2,
   text = 'Goodbye!',
   voice = '3AU1D3S2.mp3',
   deleUserId = 2,
   confuse = {'Goodbye!','Thank you!','Sorry!'},
   confuseVoice = {'3AU1D3S2.mp3','3AU1D3S2M1.mp3','3AU1D3S2M2.mp3'} ,
  },
  [13] = {
   id = 13,
   headTable = 'head',
   headId = 1,
   text = 'Bye, Miss White!',
   voice = '3AU1D3S1.mp3',
   deleUserId = 1,
   confuse = {'Bye,','Miss','White!'} ,
   confuseVoice = {'3AU1D3S1P1.mp3','3AU1D3S1P2.mp3','3AU1D3S1P3.mp3'} ,
  },
  [14] = {
   id = 14,
   headTable = 'head',
   headId = 2,
   text = 'Goodbye!',
   voice = '3AU1D3S2.mp3',
   deleUserId = 2,
   confuse = {'Goodbye!'},
   confuseVoice = {'3AU1D2S2.mp3'} ,
  },
  [15] = {
   id = 15,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Miss White.',
   voice = '3AU1D4S1.mp3',
   deleUserId = 1,
   confuse = {'Hello, I\'m Miss White.','Sorry, I\'m Miss White.','Thank you, I\'m Miss White.'},
   confuseVoice = {'3AU1D4S1.mp3','3AU1D4S1M1.mp3','3AU1D4S1M2.mp3'} ,
  },
  [16] = {
   id = 16,
   headTable = 'head',
   headId = 2,
   text = 'Hello, I\'m Wu Yifan.',
   voice = '3AU1D4S2.mp3',
   deleUserId = 2,
   confuse = {'Hello, I\'m Wu Yifan.','Hello, you are Wu Yifan.','Sorry, I\'m Wu Yifan.'},
   confuseVoice = {'3AU1D4S2.mp3','3AU1D4S2M1.mp3','3AU1D4S2M2.mp3'} ,
  },
  [17] = {
   id = 17,
   headTable = 'head',
   headId = 3,
   text = 'Hi, I\'m Sarah.',
   voice = '3AU1D4S3.mp3',
   deleUserId = 0,
   confuse = {},
   confuseVoice = {},
  },
  [18] = {
   id = 18,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Miss White.',
   voice = '3AU1D4S1.mp3',
   deleUserId = 1,
   confuse = {'Hello,','I\'m','Miss','White.'} ,
   confuseVoice = {'3AU1D4S1P1.mp3','3AU1D4S1P2.mp3','3AU1D4S1P3.mp3','3AU1D4S1P4.mp3'} ,
  },
  [19] = {
   id = 19,
   headTable = 'head',
   headId = 2,
   text = 'Hello, I\'m Wu Yifan.',
   voice = '3AU1D4S2.mp3',
   deleUserId = 2,
   confuse = {'Hello,','I\'m','Wu Yifan.'} ,
   confuseVoice = {'3AU1D4S2P1.mp3','3AU1D4S2P2.mp3','3AU1D4S2P3.mp3'} ,
  },
  [20] = {
   id = 20,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Mike.',
   voice = '3AU1D5S1.mp3',
   deleUserId = 1,
   confuse = {'Hello, I\'m Mike.','Hello, you are Mike.','Goodbye, this is Mike.'},
   confuseVoice = {'3AU1D5S1.mp3','3AU1D5S1M1.mp3','3AU1D5S1M2.mp3'} ,
  },
  [21] = {
   id = 21,
   headTable = 'head',
   headId = 1,
   text = 'What\'s your name?',
   voice = '3AU1D5S2.mp3',
   deleUserId = 1,
   confuse = {'What\'s your name?','What you name?','How are your name?'},
   confuseVoice = {'3AU1D5S2.mp3','3AU1D5S2M1.mp3','3AU1D5S2M2.mp3'} ,
  },
  [22] = {
   id = 22,
   headTable = 'head',
   headId = 2,
   text = 'My name\'s John.',
   voice = '3AU1D5S3.mp3',
   deleUserId = 2,
   confuse = {'My name\'s John.','His name is John.','My name are John.'},
   confuseVoice = {'3AU1D5S3.mp3','3AU1D5S3M1.mp3','3AU1D5S3M2.mp3'} ,
  },
  [23] = {
   id = 23,
   headTable = 'head',
   headId = 1,
   text = 'Hello, I\'m Mike.',
   voice = '3AU1D5S1.mp3',
   deleUserId = 1,
   confuse = {'Hello,','I\'m','Mike.'} ,
   confuseVoice = {'3AU1D5S1P1.mp3','3AU1D5S1P2.mp3','3AU1D5S1P3.mp3'} ,
  },
  [24] = {
   id = 24,
   headTable = 'head',
   headId = 1,
   text = 'What\'s your name?',
   voice = '3AU1D5S2.mp3',
   deleUserId = 1,
   confuse = {'What\'s',' your','name?'},
   confuseVoice = {'3AU1D5S2P1.mp3','3AU1D5S2P2.mp3','3AU1D5S2P3.mp3'} ,
  },
  [25] = {
   id = 25,
   headTable = 'head',
   headId = 2,
   text = 'My name\'s John.',
   voice = '3AU1D5S3.mp3',
   deleUserId = 2,
   confuse = {'My',' name\'s','John.'},
   confuseVoice = {'3AU1D5S3P1.mp3','3AU1D5S3P2.mp3','3AU1D5S3P3.mp3'} ,
  },
  [26] = {
   id = 26,
   headTable = 'head',
   headId = 1,
   text = 'Hello!',
   voice = '3AU1D6S1.mp3',
   deleUserId = 1,
   confuse = {'Hello!','Thank you!','Sorry!'},
   confuseVoice = {'3AU1D6S1.mp3','3AU1D6S1M1.mp3','3AU1D6S1M2.mp3'} ,
  },
  [27] = {
   id = 27,
   headTable = 'head',
   headId = 2,
   text = 'Hi! Who\'s there?',
   voice = '3AU1D6S2.mp3',
   deleUserId = 2,
   confuse = {'Hi! Who\'s there?','Goodbye! Who\'s there?','Excuse me!'},
   confuseVoice = {'3AU1D6S2.mp3','3AU1D6S2M1.mp3','3AU1D6S2M2.mp3'} ,
  },
  [28] = {
   id = 28,
   headTable = 'head',
   headId = 1,
   text = 'Guess!',
   voice = '3AU1D6S3.mp3',
   deleUserId = 1,
   confuse = {'Guess!','Sorry!','Thank you!'},
   confuseVoice = {'3AU1D6S3.mp3','3AU1D6S3M1.mp3','3AU1D6S3M2.mp3'} ,
  },
  [29] = {
   id = 29,
   headTable = 'head',
   headId = 2,
   text = 'Are you Tutu?',
   voice = '3AU1D6S4.mp3',
   deleUserId = 2,
   confuse = {'Are you Tutu?','I am Tutu.','Is you Tutu?'},
   confuseVoice = {'3AU1D6S4.mp3','3AU1D6S4M1.mp3','3AU1D6S4M2.mp3'} ,
  },
  [30] = {
   id = 30,
   headTable = 'head',
   headId = 1,
   text = 'No! Haha! I\'m Zip!',
   voice = '3AU1D6S5.mp3',
   deleUserId = 1,
   confuse = {'No! Haha! I\'m Zip!','Thank you! I\'m Zip!','Sorry, I\'m Zip!'},
   confuseVoice = {'3AU1D6S5.mp3','3AU1D6S5M1.mp3','3AU1D6S5M2.mp3'} ,
  },
  [31] = {
   id = 31,
   headTable = 'head',
   headId = 2,
   text = 'Hi, Zip! My name\'s Zoom.',
   voice = '3AU1D6S6.mp3',
   deleUserId = 2,
   confuse = {'Hi, Zip! My name\'s Zoom.','Nice meet you, Zoom.','Goodbye, Zip! My name are Zoom.'},
   confuseVoice = {'3AU1D6S6.mp3','3AU1D6S6M1.mp3','3AU1D6S6M2.mp3'} ,
  },
  [32] = {
   id = 32,
   headTable = 'head',
   headId = 2,
   text = 'Let\'s play! OK?',
   voice = '3AU1D6S7.mp3',
   deleUserId = 2,
   confuse = {'Let\'s play! OK?','Let me play! OK?','Let\'s playing! OK?'},
   confuseVoice = {'3AU1D6S7.mp3','3AU1D6S7M1.mp3','3AU1D6S7M2.mp3'} ,
  },
  [33] = {
   id = 33,
   headTable = 'head',
   headId = 1,
   text = 'Great!',
   voice = '3AU1D6S8.mp3',
   deleUserId = 1,
   confuse = {'Great!','Hello!','Thank you!'},
   confuseVoice = {'3AU1D6S8.mp3','3AU1D6S8M1.mp3','3AU1D6S8M2.mp3'} ,
  },
  [34] = {
   id = 34,
   headTable = 'head',
   headId = 1,
   text = 'Hello!',
   voice = '3AU1D6S1.mp3',
   deleUserId = 1,
   confuse = {'Hello!'},
   confuseVoice = {'3AU1D6S1.mp3'} ,
  },
  [35] = {
   id = 35,
   headTable = 'head',
   headId = 2,
   text = 'Hi! Who\'s there?',
   voice = '3AU1D6S2.mp3',
   deleUserId = 2,
   confuse = {'Hi!','Who\'s','there?'} ,
   confuseVoice = {'3AU1D6S2P1.mp3','3AU1D6S2P2.mp3','3AU1D6S2P3.mp3'} ,
  },
  [36] = {
   id = 36,
   headTable = 'head',
   headId = 1,
   text = 'Guess!',
   voice = '3AU1D6S3.mp3',
   deleUserId = 1,
   confuse = {'Guess!'},
   confuseVoice = {'3AU1D6S3.mp3'} ,
  },
  [37] = {
   id = 37,
   headTable = 'head',
   headId = 2,
   text = 'Are you Tutu?',
   voice = '3AU1D6S4.mp3',
   deleUserId = 2,
   confuse = {'Are',' you','Tutu?'},
   confuseVoice = {'3AU1D6S4P1.mp3','3AU1D6S4P2.mp3','3AU1D6S4P3.mp3'} ,
  },
  [38] = {
   id = 38,
   headTable = 'head',
   headId = 1,
   text = 'No! Haha! I\'m Zip!',
   voice = '3AU1D6S5.mp3',
   deleUserId = 1,
   confuse = {'No!','Haha!','I\'m Zip!'} ,
   confuseVoice = {'3AU1D6S5P1.mp3','3AU1D6S5P2.mp3','3AU1D6S5P3.mp3'} ,
  },
  [39] = {
   id = 39,
   headTable = 'head',
   headId = 2,
   text = 'Hi, Zip! My name\'s Zoom.',
   voice = '3AU1D6S6.mp3',
   deleUserId = 2,
   confuse = {'Hi, Zip!','My','name\'s','Zoom.'},
   confuseVoice = {'3AU1D6S6P1.mp3','3AU1D6S6P2.mp3','3AU1D6S6P3.mp3','3AU1D6S6P4.mp3'} ,
  },
  [40] = {
   id = 40,
   headTable = 'head',
   headId = 2,
   text = 'Let\'s play! OK?',
   voice = '3AU1D6S7.mp3',
   deleUserId = 2,
   confuse = {'Let\'s','play!','OK?'},
   confuseVoice = {'3AU1D6S7P1.mp3','3AU1D6S7P2.mp3','3AU1D6S7P3.mp3'} ,
  },
  [41] = {
   id = 41,
   headTable = 'head',
   headId = 1,
   text = 'Great!',
   voice = '3AU1D6S8.mp3',
   deleUserId = 1,
   confuse = {'Great!'} ,
   confuseVoice = {'3AU1D6S8.mp3'} ,
  },
  [42] = {
   id = 42,
   headTable = 'head',
   headId = 1,
   text = 'Good afternoon, Yifan.',
   voice = '3AU2D1S1.mp3',
   deleUserId = 1,
   confuse = {'Good afternoon, Yifan.','Good morning, Yifan.','Nice to meet you.'},
   confuseVoice = {'3AU2D1S1.mp3','3AU2D1S1M1.mp3','3AU2D1S1M2.mp3'} ,
  },
  [43] = {
   id = 43,
   headTable = 'head',
   headId = 2,
   text = 'Good afternoon.',
   voice = '3AU2D1S2.mp3',
   deleUserId = 2,
   confuse = {'Good afternoon.','Nice to meet you.','Fine, thank you.'},
   confuseVoice = {'3AU2D1S2.mp3','3AU2D1S2M1.mp3','3AU2D1S2M2.mp3'} ,
  },
  [44] = {
   id = 44,
   headTable = 'head',
   headId = 1,
   text = 'Good afternoon, Yifan.',
   voice = '3AU2D1S1.mp3',
   deleUserId = 1,
   confuse = {'Good,','afternoon,','Yifan.'} ,
   confuseVoice = {'3AU2D1S1P1.mp3','3AU2D1S1P2.mp3','3AU2D1S1P3.mp3'} ,
  },
  [45] = {
   id = 45,
   headTable = 'head',
   headId = 2,
   text = 'Good afternoon.',
   voice = '3AU2D1S2.mp3',
   deleUserId = 2,
   confuse = {'Good','afternoon.'},
   confuseVoice = {'3AU2D1S2P1.mp3','3AU2D1S2P2.mp3'} ,
  },
  [46] = {
   id = 46,
   headTable = 'head',
   headId = 1,
   text = 'Dad,this is Mr Jones.',
   voice = '3AU2D2S1.mp3',
   deleUserId = 1,
   confuse = {'Dad, this is Mr Jones.','Dad, this are Mr Jones.','Dad, that are Mr Jones.'},
   confuseVoice = {'3AU2D2S1.mp3','3AU2D2S1M1.mp3','3AU2D2S1M2.mp3'} ,
  },
  [47] = {
   id = 47,
   headTable = 'head',
   headId = 3,
   text = 'Nice to meet you.',
   voice = '3AU2D2S2.mp3',
   deleUserId = 0,
   confuse = {},
   confuseVoice = {},
  },
  [48] = {
   id = 48,
   headTable = 'head',
   headId = 2,
   text = 'Nice to meet you, too.',
   voice = '3AU2D2S3.mp3',
   deleUserId = 2,
   confuse = {'Nice to meet you, too.','What\'s your name?','Nice meet you, too.'},
   confuseVoice = {'3AU2D2S3.mp3','3AU2D2S3M1.mp3','3AU2D2S3M2.mp3'} ,
  },
  [49] = {
   id = 49,
   headTable = 'head',
   headId = 1,
   text = 'Dad, this is Mr Jones.',
   voice = '3AU2D2S1.mp3',
   deleUserId = 1,
   confuse = {'Dad,','this','is','Mr Jones.'},
   confuseVoice = {'3AU2D2S1P1.mp3','3AU2D2S1P2.mp3','3AU2D2S1P3.mp3','3AU2D2S1P4.mp3'},
  },
  [50] = {
   id = 50,
   headTable = 'head',
   headId = 2,
   text = 'Nice to meet you, too.',
   voice = '3AU2D2S3.mp3',
   deleUserId = 2,
   confuse = {'Nice','to','meet you,','too.'},
   confuseVoice = {'3AU2D2S3P1.mp3','3AU2D2S3P2.mp3','3AU2D2S3P3.mp3','3AU2D2S3P4.mp3'} ,
  },
  [51] = {
   id = 51,
   headTable = 'head',
   headId = 1,
   text = 'Hi, Miss White!',
   voice = '3AU2D3S1.mp3',
   deleUserId = 1,
   confuse = {'Hi, Miss White!','Goodbye, Miss White.','What\'s your name, Miss White?'},
   confuseVoice = {'3AU2D3S1.mp3','3AU2D3S1M1.mp3','3AU2D3S1M2.mp3'} ,
  },
  [52] = {
   id = 52,
   headTable = 'head',
   headId = 2,
   text = 'Hello,Mr Jones.',
   voice = '3AU2D3S2.mp3',
   deleUserId = 2,
   confuse = {'Hello, Mr Jones.','Goodbye, Miss White.','What\'s your name, Mr Jones? '},
   confuseVoice = {'3AU2D3S2.mp3','3AU2D3S2M1.mp3','3AU2D3S2M2.mp3'} ,
  },
  [53] = {
   id = 53,
   headTable = 'head',
   headId = 2,
   text = 'This is Miss Green.',
   voice = '3AU2D3S3.mp3',
   deleUserId = 2,
   confuse = {'This is Miss Green.','Nice to meet you.','Good afternoon. Nice to meet you.'},
   confuseVoice = {'3AU2D3S3.mp3','3AU2D3S3M1.mp3','3AU2D3S3M2.mp3'} ,
  },
  [54] = {
   id = 54,
   headTable = 'head',
   headId = 1,
   text = 'Good morning, Miss Green. ',
   voice = '3AU2D3S4.mp3',
   deleUserId = 1,
   confuse = {'Good morning, Miss Green.','Good night, Miss Green.','Sorry, Miss Green.'},
   confuseVoice = {'3AU2D3S4.mp3','3AU2D3S4M1.mp3','3AU2D3S4M2.mp3'} ,
  },
  [55] = {
   id = 55,
   headTable = 'head',
   headId = 3,
   text = 'Good morning.',
   voice = '3AU2D3S5.mp3',
   deleUserId = 0,
   confuse = {},
   confuseVoice = {},
  },
  [56] = {
   id = 56,
   headTable = 'head',
   headId = 1,
   text = 'Hi, Miss White!',
   voice = '3AU2D3S1.mp3',
   deleUserId = 1,
   confuse = {'Hi,','Miss White!'},
   confuseVoice = {'3AU2D3S1P1.mp3','3AU2D3S2P2.mp3'} ,
  },
  [57] = {
   id = 57,
   headTable = 'head',
   headId = 2,
   text = 'Hello, Mr Jones.',
   voice = '3AU2D3S2.mp3',
   deleUserId = 2,
   confuse = {'Hello,','Mr Jones.'},
   confuseVoice = {'3AU2D3S2P1.mp3','3AU2D3S2P2.mp3'} ,
  },
  [58] = {
   id = 58,
   headTable = 'head',
   headId = 2,
   text = 'This is Miss Green.',
   voice = '3AU2D3S3.mp3',
   deleUserId = 2,
   confuse = {'This','is','Miss Green.'},
   confuseVoice = {'3AU2D3S3P1.mp3','3AU2D3S3P2.mp3','3AU2D3S3P3.mp3'} ,
  },
  [59] = {
   id = 59,
   headTable = 'head',
   headId = 1,
   text = 'Good morning, Miss Green. ',
   voice = '3AU2D3S4.mp3',
   deleUserId = 1,
   confuse = {'Good','morning,','Miss Green.'},
   confuseVoice = {'3AU2D3S4P1.mp3','3AU2D3S4P2.mp3','3AU2D3S4P3.mp3'} ,
  },
  [60] = {
   id = 60,
   headTable = 'head',
   headId = 1,
   text = 'Hi, Mum. This is Wu Yifan.',
   voice = '3AU2D4S1.mp3',
   deleUserId = 1,
   confuse = {'Hi, Mum. This is Wu Yifan.','Hi, Mum. My name is Wu Yifan.','Excuse me. Here is Mike .'},
   confuseVoice = {'3AU2D4S1.mp3','3AU2D4S1M1.mp3,','3AU2D4S1M2.mp3'} ,
  },
  [61] = {
   id = 61,
   headTable = 'head',
   headId = 3,
   text = 'Good afternoon, Wu Yifan.',
   voice = '3AU2D4S2.mp3',
   deleUserId = 0,
   confuse = {},
   confuseVoice = {},
  },
  [62] = {
   id = 62,
   headTable = 'head',
   headId = 2,
   text = 'Good afternoon. ',
   voice = '3AU2D4S3.mp3',
   deleUserId = 2,
   confuse = {'Good afternoon. ','Good night.','Fine, thank you.'},
   confuseVoice = {'3AU2D4S3.mp3','3AU2D4S3M1.mp3','3AU2D4S3M2.mp3'} ,
  },
  [63] = {
   id = 63,
   headTable = 'head',
   headId = 2,
   text = 'Nice to meet you.',
   voice = '3AU2D4S4.mp3',
   deleUserId = 2,
   confuse = {'Nice to meet you.','Good meet you.','Nice to meeting you.'},
   confuseVoice = {'3AU2D4S4.mp3','3AU2D4S4M1.mp3','3AU2D4S4M2.mp3'} ,
  },
  [64] = {
   id = 64,
   headTable = 'head',
   headId = 3,
   text = 'Nice to meet you, too.',
   voice = '3AU2D4S5.mp3',
   deleUserId = 0,
   confuse = {},
   confuseVoice = {},
  },
  [65] = {
   id = 65,
   headTable = 'head',
   headId = 1,
   text = 'Hi,Mum. This is Wu Yifan.',
   voice = '3AU2D4S1.mp3',
   deleUserId = 1,
   confuse = {'Hi, Mum.','This','is','Wu Yifan.'},
   confuseVoice = {'3AU2D4S1P1.mp3','3AU2D4S2P2.mp3','3AU2D4S1P3.mp3','3AU2D4S2P4.mp3'} ,
  },
  [66] = {
   id = 66,
   headTable = 'head',
   headId = 2,
   text = 'Good afternoon. ',
   voice = '3AU2D4S3.mp3',
   deleUserId = 2,
   confuse = {'Good','afternoon.'},
   confuseVoice = {'3AU2D4S3P1.mp3','3AU2D4S3P2.mp3'} ,
  },
  [67] = {
   id = 67,
   headTable = 'head',
   headId = 2,
   text = 'Nice to meet you.',
   voice = '3AU2D4S4.mp3',
   deleUserId = 2,
   confuse = {'Nice','to','meet you.'},
   confuseVoice = {'3AU2D4S4P1.mp3','3AU2D4S4P2.mp3','3AU2D4S4P3.mp3'} ,
  },
  [68] = {
   id = 68,
   headTable = 'head',
   headId = 1,
   text = 'Good morning, Zoom.',
   voice = '3AU2D5S1.mp3',
   deleUserId = 1,
   confuse = {'Good morning, Zoom.','Great, Zoom.','Good morning, Zip.'},
   confuseVoice = {'3AU2D5S1.mp3','3AU2D5S1M1.mp3','3AU2D5S1M2.mp3'} ,
  },
  [69] = {
   id = 69,
   headTable = 'head',
   headId = 2,
   text = 'Good morning, Zip. ',
   voice = '3AU2D5S2.mp3',
   deleUserId = 2,
   confuse = {'Good morning, Zip.','What\'s your name?','Good night, Zip.'},
   confuseVoice = {'3AU2D5S2.mp3','3AU2D5S2M1.mp3','3AU2D5S2M2.mp3'} ,
  },
  [70] = {
   id = 70,
   headTable = 'head',
   headId = 2,
   text = 'How are you?',
   voice = '3AU2D5S3.mp3',
   deleUserId = 2,
   confuse = {'How are you?','How old are you?','Where are you?'},
   confuseVoice = {'3AU2D5S3.mp3','3AU2D5S3M1.mp3','3AU2D53S3M2.mp3'} ,
  },
  [71] = {
   id = 71,
   headTable = 'head',
   headId = 1,
   text = 'Fine, thank you.',
   voice = '3AU2D5S4.mp3',
   deleUserId = 1,
   confuse = {'Fine, thank you.','Excuse me.','Goodbye!'},
   confuseVoice = {'3AU2D5S4.mp3','3AU2D5S4M1.mp3','3AU2D5S4M2.mp3'} ,
  },
  [72] = {
   id = 72,
   headTable = 'head',
   headId = 2,
   text = 'Wow! Flowers! A red flower.',
   voice = '3AU2D5S5.mp3',
   deleUserId = 2,
   confuse = {'Wow! Flowers! A red flower.','I like flowers!','Looking! Flowers!'},
   confuseVoice = {'3AU2D5S5.mp3','3AU2D5S5M1.mp3','3AU2D5S5M2.mp3'} ,
  },
  [73] = {
   id = 73,
   headTable = 'head',
   headId = 2,
   text = 'A yellow flower.',
   voice = '3AU2D5S6.mp3',
   deleUserId = 2,
   confuse = {'A yellow flower.','Flowers!','A black flower.'},
   confuseVoice = {'3AU2D5S6.mp3','3AU2D5S6M1.mp3','3AU2D5S6M2.mp3'} ,
  },
  [74] = {
   id = 74,
   headTable = 'head',
   headId = 2,
   text = 'A blue flower.',
   voice = '3AU2D5S7.mp3',
   deleUserId = 2,
   confuse = {'A blue flower.','Good flower.','I don\'t like flower.'},
   confuseVoice = {'3AU2D5S7.mp3','3AU2D5S7M1.mp3','3AU2D53S7M2.mp3'} ,
  },
  [75] = {
   id = 75,
   headTable = 'head',
   headId = 2,
   text = 'Zip,look!',
   voice = '3AU2D5S8.mp3',
   deleUserId = 2,
   confuse = {'Zip, look!','Zip, looking!','Zip, thank you!'},
   confuseVoice = {'3AU2D5S8.mp3','3AU2D5S8M1.mp3','3AU2D5S8M2.mp3'} ,
  },
  [76] = {
   id = 76,
   headTable = 'head',
   headId = 1,
   text = 'Zoom,look!',
   voice = '3AU2D5S9.mp3',
   deleUserId = 1,
   confuse = {'Zoom, look!','Zoom, sorry!','Thank you.'},
   confuseVoice = {'3AU2D5S9.mp3','3AU2D5S9M1.mp3','3AU2D5S9M2.mp3'} ,
  },
  [77] = {
   id = 77,
   headTable = 'head',
   headId = 1,
   text = 'Good morning, Zoom.',
   voice = '3AU2D5S1.mp3',
   deleUserId = 1,
   confuse = {'Good','morning,','Zoom.'},
   confuseVoice = {'3AU2D5S1P1.mp3','3AU2D5S1P2.mp3'} ,
  },
  [78] = {
   id = 78,
   headTable = 'head',
   headId = 2,
   text = 'Good morning, Zip. ',
   voice = '3AU2D5S2.mp3',
   deleUserId = 2,
   confuse = {'Good','morning,','Zip.'},
   confuseVoice = {'3AU2D5S2P1.mp3','3AU2D5S2P2.mp3'} ,
  },
  [79] = {
   id = 79,
   headTable = 'head',
   headId = 2,
   text = 'How are you?',
   voice = '3AU2D5S3.mp3',
   deleUserId = 2,
   confuse = {'How','are','you?'},
   confuseVoice = {'3AU2D5S3P1.mp3','3AU2D5S3P2.mp3','3AU2D5S3P3.mp3'} ,
  },
  [80] = {
   id = 80,
   headTable = 'head',
   headId = 1,
   text = 'Fine,thank you.',
   voice = '3AU2D5S4.mp3',
   deleUserId = 1,
   confuse = {'Fine,','thank','you.'},
   confuseVoice = {'3AU2D5S4P1.mp3','3AU2D5S4P2.mp3','3AU2D5S4P3.mp3'} ,
  },
  [81] = {
   id = 81,
   headTable = 'head',
   headId = 2,
   text = 'Wow! Flowers! A red flower.',
   voice = '3AU2D5S5.mp3',
   deleUserId = 2,
   confuse = {'Wow! Flowers!','A','red','flower.'},
   confuseVoice = {'3AU2D5S5P1.mp3','3AU2D5S5P2.mp3','3AU2D5S5P3.mp3','3AU2D5S5P4.mp3'} ,
  },
  [82] = {
   id = 82,
   headTable = 'head',
   headId = 2,
   text = 'A yellow flower.',
   voice = '3AU2D5S6.mp3',
   deleUserId = 2,
   confuse = {'A','yellow','flower.'},
   confuseVoice = {'3AU2D5S6P1.mp3','3AU2D5S6P2.mp3,','3AU2D5S6P3.mp3'} ,
  },
  [83] = {
   id = 83,
   headTable = 'head',
   headId = 2,
   text = 'A blue flower.',
   voice = '3AU2D5S7.mp3',
   deleUserId = 2,
   confuse = {'A','blue','flower.'},
   confuseVoice = {'3AU2D5S7P1.mp3','3AU2D5S7P2.mp3,','3AU2D5S7P3.mp3'} ,
  },
  [84] = {
   id = 84,
   headTable = 'head',
   headId = 2,
   text = 'Zip, look!',
   voice = '3AU2D5S8.mp3',
   deleUserId = 2,
   confuse = {'Zip,','look!'},
   confuseVoice = {'3AU2D5S8P1.mp3','3AU2D5S8P2.mp3'} ,
  },
  [85] = {
   id = 85,
   headTable = 'head',
   headId = 1,
   text = 'Zoom, look!',
   voice = '3AU2D5S9.mp3',
   deleUserId = 1,
   confuse = {'Zoom,','look!'},
   confuseVoice = {'3AU2D5S9P1.mp3','3AU2D5S9P2.mp3'} ,
  },
}
