--[[

        2.lua
        exported by excel2lua.py
        from file:2.xlsx

--]]

return {
  [1] = {
   id = 1,
   cStatements = {'听读单词-1：观察图卡内容，对听到的单词发音进行跟读重复。','听读单词-2：观察图卡内容和四线格书写规范，对听到的单词发音进行跟读重复。'},
   statements = {'Listen and read-1','Listen and read-2'},
   voices = {'Listen and read-1.mp3','Listen and read-2.mp3'},
   tableId = 10,
   worldIds = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27},
  },
  [2] = {
   id = 2,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [3] = {
   id = 3,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [4] = {
   id = 4,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [5] = {
   id = 5,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [6] = {
   id = 6,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [7] = {
   id = 7,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [8] = {
   id = 8,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [9] = {
   id = 9,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [10] = {
   id = 10,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [11] = {
   id = 11,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [12] = {
   id = 12,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [13] = {
   id = 13,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [14] = {
   id = 14,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [15] = {
   id = 15,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [16] = {
   id = 16,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [17] = {
   id = 17,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [18] = {
   id = 18,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [19] = {
   id = 19,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [20] = {
   id = 20,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [21] = {
   id = 21,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
  [22] = {
   id = 22,
   cStatements = {},
   statements = {},
   voices = {},
   tableId = -1,
   worldIds = {},
  },
}
