--[[

        3.lua
        exported by excel2lua.py
        from file:3.xlsx

--]]

return {
  [1] = {
   id = 1,
   cStatements = {'句式1：“打招呼并向别人介绍自己。”Pattern-1:"Hello, I\'m...."','句式2：“我有什么东西...” Pattern-2："I have....."','句式3：“询问对方名字。”Pattern-3："What\'s your name?"','句式4：“介绍自己的名字。” Pattern-4："My name\'s ..."',
'句式5：“和某人说再见。” Pattern-5："Goodbye..."'},
   statements = {'根据中文提示，选出合适的英文句式表达。','观察句式的表达示范,注意使用图片旁的线索提示。','回顾示范，进行第一次尝试表达。','回顾示范，进行第二次尝试表达。'},
   steps = {'Chose the pattern','Watch the example','Try to speak-1','Try to speak-2'},
   voices = {'Chose the pattern.mp3','Watch the example.mp3','Try to speak-1.mp3','Try to speak-2.mp3'},
   tableId = 11,
   textIds = {1,2,3,4,5},
  },
  [2] = {
   id = 2,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [3] = {
   id = 3,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [4] = {
   id = 4,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [5] = {
   id = 5,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [6] = {
   id = 6,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [7] = {
   id = 7,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [8] = {
   id = 8,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [9] = {
   id = 9,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [10] = {
   id = 10,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [11] = {
   id = 11,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [12] = {
   id = 12,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [13] = {
   id = 13,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [14] = {
   id = 14,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [15] = {
   id = 15,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [16] = {
   id = 16,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [17] = {
   id = 17,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [18] = {
   id = 18,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [19] = {
   id = 19,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [20] = {
   id = 20,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [21] = {
   id = 21,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
  [22] = {
   id = 22,
   cStatements = {},
   statements = {},
   steps = {},
   voices = {},
   tableId = -1,
   textIds = {},
  },
}
