--[[

        4.lua
        exported by excel2lua.py
        from file:4.xlsx

--]]

return {
  [1] = {
   id = 1,
   headline = 'Topic-1:  Hello! 话题1:你好！ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {1,2},
  },
  [2] = {
   id = 2,
   headline = 'Topic-1:  Hello! 话题1:你好！ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {3,2},
  },
  [3] = {
   id = 3,
   headline = 'Topic-1:  Hello! 话题1:你好！ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {1,4},
  },
  [4] = {
   id = 4,
   headline = 'Topic-2:  What\'s your name? 话题2:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {5,6,7},
  },
  [5] = {
   id = 5,
   headline = 'Topic-2:  What\'s your name? 话题2:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {8,9,7},
  },
  [6] = {
   id = 6,
   headline = 'Topic-2:  What\'s your name? 话题2:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {5,6,10},
  },
  [7] = {
   id = 7,
   headline = 'Topic-3:  Goodbye! 话题3:再见！ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {11,12},
  },
  [8] = {
   id = 8,
   headline = 'Topic-3:  Goodbye! 话题3:再见！ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {13,12},
  },
  [9] = {
   id = 9,
   headline = 'Topic-3:  Goodbye! 话题3:再见！ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {11,14},
  },
  [10] = {
   id = 10,
   headline = 'Topic-4:  Hello, I\'m Miss White. 话题4:大家好，我是怀特老师。 ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {15,16,17},
  },
  [11] = {
   id = 11,
   headline = 'Topic-4:  Hello, I\'m Miss White. 话题4:大家好，我是怀特老师。 ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {18,16,17},
  },
  [12] = {
   id = 12,
   headline = 'Topic-4:  Hello, I\'m Miss White. 话题4:大家好，我是怀特老师。 ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {15,19,17},
  },
  [13] = {
   id = 13,
   headline = 'Topic-5:  What\'s your name? 话题5:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {20,21,22},
  },
  [14] = {
   id = 14,
   headline = 'Topic-5:  What\'s your name? 话题5:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {23,24,22},
  },
  [15] = {
   id = 15,
   headline = 'Topic-5:  What\'s your name? 话题5:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {20,21,25},
  },
  [16] = {
   id = 16,
   headline = 'Topic-6:  What\'s your name? 话题6:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {26,27,28,29,30,31,32,33},
  },
  [17] = {
   id = 17,
   headline = 'Topic-6:  What\'s your name? 话题6:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {34,27,36,29,38,31,32,41},
  },
  [18] = {
   id = 18,
   headline = 'Topic-6:  What\'s your name? 话题6:你叫什么名字？ ',
   cStatements = {'角色扮演A:以角色A参与完成以下对话。','角色扮演B:以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {26,35,28,37,30,39,40,33},
  },
  [19] = {
   id = 19,
   headline = 'Topic-1:  Good afternoon, Yifan. 话题1：下午好，一凡。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {42,43},
  },
  [20] = {
   id = 20,
   headline = 'Topic-1:  Good afternoon, Yifan. 话题1：下午好，一凡。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {44,43},
  },
  [21] = {
   id = 21,
   headline = 'Topic-1:  Good afternoon, Yifan. 话题1：下午好，一凡。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {42,45},
  },
  [22] = {
   id = 22,
   headline = 'Topic-2:  Nice to meet you. 话题2：很高兴见到你。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {46,47,48},
  },
  [23] = {
   id = 23,
   headline = 'Topic-2:  Nice to meet you. 话题2：很高兴见到你。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {49,47,48},
  },
  [24] = {
   id = 24,
   headline = 'Topic-2:  Nice to meet you. 话题2：很高兴见到你。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {46,47,50},
  },
  [25] = {
   id = 25,
   headline = 'Topic-3:  Good morning,Miss Green. 话题2：早上好，格林老师。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {51,52,53,54,55},
  },
  [26] = {
   id = 26,
   headline = 'Topic-3:  Good morning,Miss Green. 话题2：早上好，格林老师。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {56,52,53,59,55},
  },
  [27] = {
   id = 27,
   headline = 'Topic-3:  Good morning,Miss Green. 话题2：早上好，格林老师。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {51,57,58,54,55},
  },
  [28] = {
   id = 28,
   headline = 'Topic-4:  This is Wu Yifan. 话题4：这是吴一凡。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {60,61,62,63,64},
  },
  [29] = {
   id = 29,
   headline = 'Topic-4:  This is Wu Yifan. 话题4：这是吴一凡。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {65,61,62,63,64},
  },
  [30] = {
   id = 30,
   headline = 'Topic-4:  This is Wu Yifan. 话题4：这是吴一凡。 ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {60,61,66,67,64},
  },
  [31] = {
   id = 31,
   headline = 'Topic-5:  Wow Flowers! 话题5：哇，鲜花！ ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {68,69,70,71,72,73,74,75,76},
  },
  [32] = {
   id = 32,
   headline = 'Topic-5:  Wow Flowers! 话题5：哇，鲜花！ ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {77,69,70,80,72,73,74,75,85},
  },
  [33] = {
   id = 33,
   headline = 'Topic-5:  Wow Flowers! 话题5：哇，鲜花！ ',
   cStatements = {'角色扮演A：以角色A参与完成以下对话。','角色扮演B：以角色B参与完成以下对话。'},
   statements = {'Role play as A','Role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {68,78,79,71,81,82,83,84,76},
  },
}
