--[[

        4.lua
        exported by excel2lua.py
        from file:4.xlsx

--]]

return {
  [1] = {
   id = 1,
   headline = 'Topic-1: "Hello!" 话题1：“你好！”',
   cStatements = {'请扮演角色A，参与完成以下对话。','请扮演角色B，参与完成以下对话。'},
   statements = {'Role play as A','role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp3'},
   headTable = 'head',
   headIds = {1,2},
   tableId = 12,
   userIconStep = {1,2,3,4},
  },
  [2] = {
   id = 2,
   headline = 'Topic-2: "What\'s your name?" 话题2：“你叫什么名字？”',
   cStatements = {'请扮演角色A，参与完成以下对话。','请扮演角色B，参与完成以下对话。'},
   statements = {'Role play as A','role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp4'},
   headTable = 'head',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [3] = {
   id = 3,
   headline = 'Topic-3: "Goodbye!" 话题3：“再见！”',
   cStatements = {'请扮演角色A，参与完成以下对话。','请扮演角色B，参与完成以下对话。'},
   statements = {'Role play as A','role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp5'},
   headTable = 'head',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [4] = {
   id = 4,
   headline = 'Topic-4: "Hello, I\'m Miss White." 话题4：“大家好，我是怀特老师。”',
   cStatements = {'请扮演角色A，参与完成以下对话。','请扮演角色B，参与完成以下对话。'},
   statements = {'Role play as A','role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp6'},
   headTable = 'head',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [5] = {
   id = 5,
   headline = 'Topic-5: "What\'s your name?"话题5：“你叫什么名字？”',
   cStatements = {'请扮演角色A，参与完成以下对话。','请扮演角色B，参与完成以下对话。'},
   statements = {'Role play as A','role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp7'},
   headTable = 'head',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [6] = {
   id = 6,
   headline = 'Topic-6: "What\'s your name?"话题6：“你叫什么名字？”',
   cStatements = {'请扮演角色A，参与完成以下对话。','请扮演角色B，参与完成以下对话。'},
   statements = {'Role play as A','role play as B'},
   sVoice = {'Role play as A.mp3.','role play as B.mp8'},
   headTable = 'head',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [7] = {
   id = 7,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [8] = {
   id = 8,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [9] = {
   id = 9,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = 12,
   userIconStep = {},
  },
  [10] = {
   id = 10,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [11] = {
   id = 11,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [12] = {
   id = 12,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [13] = {
   id = 13,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [14] = {
   id = 14,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [15] = {
   id = 15,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [16] = {
   id = 16,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [17] = {
   id = 17,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [18] = {
   id = 18,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [19] = {
   id = 19,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [20] = {
   id = 20,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [21] = {
   id = 21,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
  [22] = {
   id = 22,
   headline = '',
   cStatements = {},
   statements = {},
   sVoice = {},
   headTable = '',
   headIds = {},
   tableId = -1,
   userIconStep = {},
  },
}
