--[[

        5.lua
        exported by excel2lua.py
        from file:5.xlsx

--]]

return {
  [1] = {
   id = 1,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp3'},
   tableId = 10,
   matchId = 1,
   wordUnpack = {'hel','lo'},
   soundmark = {'[hə]','[ləʊ]'},
   unpackVoice = {'hello1.mp3','hello2.mp3'},
   completeVoice = '[hələʊ]',
  },
  [2] = {
   id = 2,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp4'},
   tableId = 10,
   matchId = 2,
   wordUnpack = {'wel','come'},
   soundmark = {'[\'wel][kəm]'},
   unpackVoice = {'welcome1.mp3','welcome2.mp3'},
   completeVoice = '[\'welkəm] ',
  },
  [3] = {
   id = 3,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp5'},
   tableId = 10,
   matchId = 3,
   wordUnpack = {'space','ship'},
   soundmark = {'[\'speɪs]','[ʃɪp]'},
   unpackVoice = {'spaceship1.mp3','spaceship2.mp3'},
   completeVoice = '[\'speɪsʃɪp]',
  },
  [4] = {
   id = 4,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp6'},
   tableId = 10,
   matchId = 4,
   wordUnpack = {'doc','tor'},
   soundmark = {'[\'dɒk]','[tə(r)]'},
   unpackVoice = {'doctor1.mp3','doctor2.mp3'},
   completeVoice = '[\'dɒktə(r)]',
  },
  [5] = {
   id = 5,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp7'},
   tableId = 10,
   matchId = 5,
   wordUnpack = {'name'},
   soundmark = {'[neɪm]'},
   unpackVoice = {'name.mp3'},
   completeVoice = '[neɪm]',
  },
  [6] = {
   id = 6,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp8'},
   tableId = 10,
   matchId = 6,
   wordUnpack = {'friend'},
   soundmark = {'[frend]'},
   unpackVoice = {'friend.mp3'},
   completeVoice = '[frend]',
  },
  [7] = {
   id = 7,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp9'},
   tableId = 10,
   matchId = 7,
   wordUnpack = {'nice'},
   soundmark = {'[naɪs]'},
   unpackVoice = {'nice.mp3'},
   completeVoice = ' [naɪs]',
  },
  [8] = {
   id = 8,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp10'},
   tableId = 10,
   matchId = 8,
   wordUnpack = {'meet'},
   soundmark = {'[mi:t]'},
   unpackVoice = {'meet.mp3'},
   completeVoice = '[mi:t]',
  },
  [9] = {
   id = 9,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp11'},
   tableId = 10,
   matchId = 9,
   wordUnpack = {'who'},
   soundmark = {'[huː]'},
   unpackVoice = {'who.mp3'},
   completeVoice = '[huː]',
  },
  [10] = {
   id = 10,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp12'},
   tableId = 10,
   matchId = 10,
   wordUnpack = {'there'},
   soundmark = {'[ðeə(r)]'},
   unpackVoice = {'there.mp3'},
   completeVoice = '[ðeə(r)]',
  },
  [11] = {
   id = 11,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp13'},
   tableId = 10,
   matchId = 11,
   wordUnpack = {'your'},
   soundmark = {'[jɔː(r)]'},
   unpackVoice = {'your.mp3'},
   completeVoice = '[jɔː(r)]',
  },
  [12] = {
   id = 12,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp14'},
   tableId = 10,
   matchId = 12,
   wordUnpack = {'bag'},
   soundmark = {'[bæg]'},
   unpackVoice = {'bag.mp3'},
   completeVoice = '[bæg]',
  },
  [13] = {
   id = 13,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp15'},
   tableId = 10,
   matchId = 13,
   wordUnpack = {'o','pen'},
   soundmark = {'[\'əʊ]','[pən]'},
   unpackVoice = {'open1.mp3','open2.mp3'},
   completeVoice = '[\'əʊpən]',
  },
  [14] = {
   id = 14,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp16'},
   tableId = 10,
   matchId = 14,
   wordUnpack = {'ru','ler'},
   soundmark = {'[\'ruː]','[lə(r)]'},
   unpackVoice = {'ruler1.mp3','ruler2.mp3'},
   completeVoice = '[\'ruːlə(r)]',
  },
  [15] = {
   id = 15,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp17'},
   tableId = 10,
   matchId = 15,
   wordUnpack = {'pen','cil'},
   soundmark = {'[\'pen]','[sl]'},
   unpackVoice = {'pencil1.mp3','pencil2.mp3'},
   completeVoice = '[\'pensl]',
  },
  [16] = {
   id = 16,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp18'},
   tableId = 10,
   matchId = 16,
   wordUnpack = {'e','ra','ser'},
   soundmark = {'[ɪ]','[\'reɪ]','[zə(r)]'},
   unpackVoice = {'eraser1.mp3','eraser2.mp3','eraser3.mp3'},
   completeVoice = '[ɪ\'reɪzə(r)]',
  },
  [17] = {
   id = 17,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp19'},
   tableId = 10,
   matchId = 17,
   wordUnpack = {'cray','on'},
   soundmark = {'[\'kreɪ]','[ən]'},
   unpackVoice = {'crayon1.mp3','crayon2.mp3'},
   completeVoice = '[\'kreɪən]',
  },
  [18] = {
   id = 18,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp20'},
   tableId = 10,
   matchId = 18,
   wordUnpack = {'pen'},
   soundmark = {'[pen]'},
   unpackVoice = {'pen.mp3'},
   completeVoice = '[pen]',
  },
  [19] = {
   id = 19,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp21'},
   tableId = 10,
   matchId = 19,
   wordUnpack = {'pen','cil','box'},
   soundmark = {'[\'pen]]','[sl]','[bɒks]'},
   unpackVoice = {'pencilbox1.mp3','pencilbox2.mp3','pencilbox3.mp3'},
   completeVoice = '[\'penslbɒks]',
  },
  [20] = {
   id = 20,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp22'},
   tableId = 10,
   matchId = 20,
   wordUnpack = {'book'},
   soundmark = {'[bʊk]'},
   unpackVoice = {'book.mp3'},
   completeVoice = '[bʊk]',
  },
  [21] = {
   id = 21,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp23'},
   tableId = 10,
   matchId = 21,
   wordUnpack = {'touch'},
   soundmark = {'[tʌtʃ]'},
   unpackVoice = {'touch.mp3'},
   completeVoice = '[tʌtʃ]',
  },
  [22] = {
   id = 22,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp24'},
   tableId = 10,
   matchId = 22,
   wordUnpack = {'badge'},
   soundmark = {'[bædʒ]'},
   unpackVoice = {'badge.mp3'},
   completeVoice = '[bædʒ]',
  },
  [23] = {
   id = 23,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp25'},
   tableId = 10,
   matchId = 23,
   wordUnpack = {'cool'},
   soundmark = {'[ku:l]'},
   unpackVoice = {'cool.mp3'},
   completeVoice = '[ku:l]',
  },
  [24] = {
   id = 24,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp26'},
   tableId = 10,
   matchId = 24,
   wordUnpack = {'sword'},
   soundmark = {'[sɔːd]'},
   unpackVoice = {'sword.mp3'},
   completeVoice = '[sɔːd]',
  },
  [25] = {
   id = 25,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp27'},
   tableId = 10,
   matchId = 25,
   wordUnpack = {'gun'},
   soundmark = {'[gʌn]'},
   unpackVoice = {'gun.mp3'},
   completeVoice = '[gʌn]',
  },
  [26] = {
   id = 26,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp28'},
   tableId = 10,
   matchId = 26,
   wordUnpack = {'thank'},
   soundmark = {'[θæŋk]'},
   unpackVoice = {'thank.mp3'},
   completeVoice = '[θæŋk]',
  },
  [27] = {
   id = 27,
   cStatements = {'请根据单词的音节划分及演化，推断并拼读出整词的发音。','回忆单词及音节发音，找回缺失的元音字母。'},
   statements = {'Spell by syllables','Find vowels'},
   sVoice = {'Spell by syllables.mp3','Find vowels.mp29'},
   tableId = 10,
   matchId = 27,
   wordUnpack = {'no'},
   soundmark = {'[nəʊ]'},
   unpackVoice = {'no.mp3'},
   completeVoice = '[nəʊ]',
  },
}
