--[[

        7.lua
        exported by excel2lua.py
        from file:7.xlsx

--]]

return {
  [1] = {
   id = 1,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'hello.jpg',
   wordVoice = 'hello.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [2] = {
   id = 2,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp4'},
   icon = 'welcome',
   wordVoice = 'welcome.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [3] = {
   id = 3,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp5'},
   icon = 'spaceship',
   wordVoice = 'spaceship.mp3',
   expandWord = {'a spaceship','spaceships','a spaceship','spaceships'},
   expandVoice = {'spaceship(a spaceship).mp3','spaceship(spaceships).mp3','spaceship(a spaceship).mp3','spaceship(spaceships).mp3'},
   expandIcon = {'spaceship-1.jpg','spaceships-1.jpg','spaceship-2.jpg','spaceships-2.jpg'},
  },
  [4] = {
   id = 4,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp6'},
   icon = 'Dr.',
   wordVoice = 'doctor.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [5] = {
   id = 5,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp7'},
   icon = 'name',
   wordVoice = 'name.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [6] = {
   id = 6,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp8'},
   icon = 'friend',
   wordVoice = 'friend.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [7] = {
   id = 7,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp9'},
   icon = 'nice',
   wordVoice = 'nice.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [8] = {
   id = 8,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp10'},
   icon = 'meet',
   wordVoice = 'meet.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [9] = {
   id = 9,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp11'},
   icon = 'who',
   wordVoice = 'who.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [10] = {
   id = 10,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp12'},
   icon = 'there',
   wordVoice = 'there.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [11] = {
   id = 11,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp13'},
   icon = 'your',
   wordVoice = 'your.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [12] = {
   id = 12,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp14'},
   icon = 'bag',
   wordVoice = 'bag.mp3',
   expandWord = {'carry your bag','carry your bag'},
   expandVoice = {'bag(carry your bag).mp3','bag(carry your bag).mp3'},
   expandIcon = {'bag(carry your bag)-1.jpg','bag(carry your bag)-2.jpg'},
  },
  [13] = {
   id = 13,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp15'},
   icon = 'open',
   wordVoice = 'open.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [14] = {
   id = 14,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp16'},
   icon = 'ruler',
   wordVoice = 'ruler.mp3',
   expandWord = {'a ruler','rulers','a ruler','rulers'},
   expandVoice = {'ruler(a ruler).mp3','ruler(rulers).mp3','ruler(a ruler).mp3','ruler(rulers).mp3'},
   expandIcon = {'ruler-1.jpg','rulers-1.jpg,ruler-2.jpg','rulers-2.jpg'},
  },
  [15] = {
   id = 15,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp17'},
   icon = 'pencil',
   wordVoice = 'pencil.mp3',
   expandWord = {'a pencil','pencils','a pencil','pencils'},
   expandVoice = {'pencil(a pencil).mp3','pencil(pencils).mp3','pencil(a pencil).mp3','pencil(pencils).mp3'},
   expandIcon = {'pencil-1.jpg','pencils-1','pencil-2','pencils-2'},
  },
  [16] = {
   id = 16,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp18'},
   icon = 'eraser',
   wordVoice = 'eraser.mp3',
   expandWord = {'an eraser','erasers','an eraser','erasers'},
   expandVoice = {'eraser(an eraser).mp3','eraser(erasers).mp3','eraser(an eraser).mp3','eraser(erasers).mp3,'},
   expandIcon = {'eraser-1.jpg','erasers-1.jpg','eraser-2.jpg','erasers-2.jpg'},
  },
  [17] = {
   id = 17,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp19'},
   icon = 'crayon',
   wordVoice = 'crayon.mp3',
   expandWord = {'a crayon','crayons','a crayon','crayons'},
   expandVoice = {'crayon(a crayon).mp3','crayon(crayons).mp3','crayon(a crayon).mp3','crayon(crayons).mp3'},
   expandIcon = {'crayon-1.jpg','crayons-1.jpg','crayon-2.jpg','crayons-2.jpg'},
  },
  [18] = {
   id = 18,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp20'},
   icon = 'pen',
   wordVoice = 'pen.mp3',
   expandWord = {'show me your pen','show me your pen'},
   expandVoice = {'pen(show me your pen).mp3','pen(show me your pen).mp3'},
   expandIcon = {'pen(show me your pen)-1.jpg','pen(show me your pen)-2.jpg'},
  },
  [19] = {
   id = 19,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp21'},
   icon = 'pencil box  ',
   wordVoice = 'pencil box.mp3  ',
   expandWord = {'open your pencilbox'},
   expandVoice = {'pencilbox(open your pencilbox).mp3','pencilbox(open your pencilbox).mp3'},
   expandIcon = {'pencilbox(open your pencilbox)-1.jpg','pencilbox(open your pencilbox)-2.jpg'},
  },
  [20] = {
   id = 20,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp22'},
   icon = 'book',
   wordVoice = 'book.mp3',
   expandWord = {'close your book'},
   expandVoice = {'book(close your book).mp3','book(close your book).mp3'},
   expandIcon = {'book(close your book)-1.jpg','book(close your book)-2.jpg'},
  },
  [21] = {
   id = 21,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp23'},
   icon = 'touch',
   wordVoice = 'touch.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [22] = {
   id = 22,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp24'},
   icon = 'badge',
   wordVoice = 'badge.mp3',
   expandWord = {'a badge','badges','a badge','badges'},
   expandVoice = {'badge(a badge).mp3','badge(badges).mp3','badge(a badge).mp3','badge(badges).mp3'},
   expandIcon = {'badge-1','badges-1','badge-2','badges-2'},
  },
  [23] = {
   id = 23,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp25'},
   icon = 'cool',
   wordVoice = 'cool.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [24] = {
   id = 24,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp26'},
   icon = 'sword',
   wordVoice = 'sword.mp3',
   expandWord = {'a sword','swords','a sword','swords'},
   expandVoice = {'sword(a sword).mp3','sword(swords).mp3','sword(a sword).mp3','sword(swords).mp3'},
   expandIcon = {'sword-1','swords-1','sword-2','swords-2'},
  },
  [25] = {
   id = 25,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp27'},
   icon = 'gun',
   wordVoice = 'gun.mp3',
   expandWord = {'a gun','guns','a gun','guns'},
   expandVoice = {'gun(a gun).mp3','gun(guns).mp3','gun(a gun).mp3','gun(guns).mp3'},
   expandIcon = {'gun-1','guns-1','gun-2','guns-2'},
  },
  [26] = {
   id = 26,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp28'},
   icon = 'thank',
   wordVoice = 'thank.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [27] = {
   id = 27,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp29'},
   icon = 'no',
   wordVoice = 'no.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [28] = {
   id = 28,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'morning',
   wordVoice = 'morning.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [29] = {
   id = 29,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'this',
   wordVoice = 'this.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [30] = {
   id = 30,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'too',
   wordVoice = 'too.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [31] = {
   id = 31,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'kid',
   wordVoice = 'kid.mp3',
   expandWord = {'a kid','kids','a kid','kids'},
   expandVoice = {'kid(a kid).mp3','kid(kids).mp3','a kid.mp3','kids.mp3'},
   expandIcon = {'kid-1.jpg','kids-1.jpg','kid-2.jpg','kids-2.jpg'},
  },
  [32] = {
   id = 32,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'fine',
   wordVoice = 'fine.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [33] = {
   id = 33,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'so',
   wordVoice = 'so.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [34] = {
   id = 34,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'many',
   wordVoice = 'many.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [35] = {
   id = 35,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'planet',
   wordVoice = 'planet.mp3',
   expandWord = {'a planet','planets','a planet','planets'},
   expandVoice = {'planet(a planet).mp3','planet(planets).mp3','a planet.mp3','planets.mp3'},
   expandIcon = {'planet-1.jpg','planets-1.jpg','planet-2.jpg','planets-2.jpg'},
  },
  [36] = {
   id = 36,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'red',
   wordVoice = 'red.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [37] = {
   id = 37,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'white',
   wordVoice = 'white.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [38] = {
   id = 38,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'yellow',
   wordVoice = 'yellow.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [39] = {
   id = 39,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'green',
   wordVoice = 'green.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [40] = {
   id = 40,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'brown',
   wordVoice = 'brown.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [41] = {
   id = 41,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'orange',
   wordVoice = 'orange.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [42] = {
   id = 42,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'blue',
   wordVoice = 'blue.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [43] = {
   id = 43,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'one',
   wordVoice = 'one.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [44] = {
   id = 44,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'home',
   wordVoice = 'home.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [45] = {
   id = 45,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'miss',
   wordVoice = 'miss.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [46] = {
   id = 46,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'upset',
   wordVoice = 'upset.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [47] = {
   id = 47,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'everybody',
   wordVoice = 'everybody.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [48] = {
   id = 48,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'black',
   wordVoice = 'black.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [49] = {
   id = 49,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'button',
   wordVoice = 'button.mp3',
   expandWord = {'a button','buttons','a button','buttons'},
   expandVoice = {'button(a button).mp3','button(buttons).mp3','a button.mp3','buttons.mp3'},
   expandIcon = {'button-1.jpg','buttons-1.jpg','button-2.jpg','buttons-2.jpg'},
  },
  [50] = {
   id = 50,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'target',
   wordVoice = 'target.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [51] = {
   id = 51,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'push',
   wordVoice = 'push.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [52] = {
   id = 52,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'full',
   wordVoice = 'full.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [53] = {
   id = 53,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'speed',
   wordVoice = 'speed.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [54] = {
   id = 54,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'ahead',
   wordVoice = 'ahead.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [55] = {
   id = 55,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'stand up ',
   wordVoice = 'stand up.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [56] = {
   id = 56,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'sit down',
   wordVoice = 'sit down.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [57] = {
   id = 57,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'OK',
   wordVoice = 'OK.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [58] = {
   id = 58,
   cStatements = {'单词拼写：根据图卡内容，回顾单词并将字母正确排序。','拓展应用：根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'mum',
   wordVoice = 'mum.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
}
