--[[

        7.lua
        exported by excel2lua.py
        from file:7.xlsx

--]]

return {
  [1] = {
   id = 1,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp3'},
   icon = 'hello',
   wordVoice = 'hello.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [2] = {
   id = 2,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp4'},
   icon = 'welcome',
   wordVoice = 'welcome.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [3] = {
   id = 3,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp5'},
   icon = 'spaceship',
   wordVoice = 'spaceship.mp3',
   expandWord = {'a spaceship','spaceships，a spaceship','spaceships，'},
   expandVoice = {'a spaceship.mp3','spaceships.mp3,a spaceship.mp3','spaceships.mp3'},
   expandIcon = {'spaceship-1.jpg','spaceships-2.jpg,spaceship-2.jpg','spaceships-2.jpg'},
  },
  [4] = {
   id = 4,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp6'},
   icon = 'Dr.',
   wordVoice = 'doctor.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [5] = {
   id = 5,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp7'},
   icon = 'name',
   wordVoice = 'name.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [6] = {
   id = 6,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp8'},
   icon = 'friend',
   wordVoice = 'friend.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [7] = {
   id = 7,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp9'},
   icon = 'nice',
   wordVoice = 'nice.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [8] = {
   id = 8,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp10'},
   icon = 'meet',
   wordVoice = 'meet.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [9] = {
   id = 9,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp11'},
   icon = 'who',
   wordVoice = 'who.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [10] = {
   id = 10,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp12'},
   icon = 'there',
   wordVoice = 'there.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [11] = {
   id = 11,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp13'},
   icon = 'your',
   wordVoice = 'your.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [12] = {
   id = 12,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp14'},
   icon = 'bag',
   wordVoice = 'bag.mp3',
   expandWord = {'carry your bag'},
   expandVoice = {'carry your bag.mp3'},
   expandIcon = {'carry your bag.jpg'},
  },
  [13] = {
   id = 13,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp15'},
   icon = 'open',
   wordVoice = 'open.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [14] = {
   id = 14,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp16'},
   icon = 'ruler',
   wordVoice = 'ruler.mp3',
   expandWord = {'a ruler','rulers，a ruler','rulers，'},
   expandVoice = {'a ruler.mp3','rulers.mp3,a ruler.mp3','rulers.mp3'},
   expandIcon = {'ruler-1.jpg','rulers-1.jpg,ruler-2.jpg','rulers-2.jpg'},
  },
  [15] = {
   id = 15,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp17'},
   icon = 'pencil',
   wordVoice = 'pencil.mp3',
   expandWord = {'a pencil','pencils,a pencil','pencils'},
   expandVoice = {'a pencil.mp3','pencils.mp3,a pencil.mp3','pencils.mp3'},
   expandIcon = {},
  },
  [16] = {
   id = 16,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp18'},
   icon = 'eraser',
   wordVoice = 'eraser.mp3',
   expandWord = {'an eraser','erasers,an eraser','erasers'},
   expandVoice = {},
   expandIcon = {},
  },
  [17] = {
   id = 17,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp19'},
   icon = 'crayon',
   wordVoice = 'crayon.mp3',
   expandWord = {'a crayon','crayons,a crayon','crayons'},
   expandVoice = {},
   expandIcon = {},
  },
  [18] = {
   id = 18,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp20'},
   icon = 'pen',
   wordVoice = 'pen.mp3',
   expandWord = {'show me your pen'},
   expandVoice = {},
   expandIcon = {},
  },
  [19] = {
   id = 19,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp21'},
   icon = 'pencil box  ',
   wordVoice = 'pencil box.mp3  ',
   expandWord = {'open your pencil pencilbox'},
   expandVoice = {},
   expandIcon = {},
  },
  [20] = {
   id = 20,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp22'},
   icon = 'book',
   wordVoice = 'book.mp3',
   expandWord = {'close your book'},
   expandVoice = {},
   expandIcon = {},
  },
  [21] = {
   id = 21,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp23'},
   icon = 'touch',
   wordVoice = 'touch.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [22] = {
   id = 22,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp24'},
   icon = 'badge',
   wordVoice = 'badge.mp3',
   expandWord = {'a badge','badges,a badge','badges'},
   expandVoice = {},
   expandIcon = {},
  },
  [23] = {
   id = 23,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp25'},
   icon = 'cool',
   wordVoice = 'cool.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [24] = {
   id = 24,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp26'},
   icon = 'sword',
   wordVoice = 'sword.mp3',
   expandWord = {'a sword','swords,a sword','swords'},
   expandVoice = {},
   expandIcon = {},
  },
  [25] = {
   id = 25,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp27'},
   icon = 'gun',
   wordVoice = 'gun.mp3',
   expandWord = {'a gun','guns,a gun','guns'},
   expandVoice = {},
   expandIcon = {},
  },
  [26] = {
   id = 26,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp28'},
   icon = 'thank',
   wordVoice = 'thank.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
  [27] = {
   id = 27,
   cStatements = {'根据图卡内容，回顾单词并将字母正确排序。','根据给出的案例，完成单词拓展认读。'},
   statements = {'Spell the word','Extend learning'},
   voice = {'Spell the word.mp3','Extend learning.mp29'},
   icon = 'no',
   wordVoice = 'no.mp3',
   expandWord = {},
   expandVoice = {},
   expandIcon = {},
  },
}
