--[[

        8.lua
        exported by excel2lua.py
        from file:8.xlsx

--]]

return {
  [1] = {
   id = 1,
   cStatements = {'看图卡，朗读出正确的单词。','根据图卡输入单词。','根据发音，从图组中选出意思相匹配的单词。'},
   statements = {'Read the word','Spell the word','Listen and tick'},
   voice = {'Read the word.mp3','Spell the word.mp3','Listen and tick.mp3'},
   tableId = 10,
   wordId = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27},
   weight = {30,30,40},
   chaosTableId = 13,
   textId = {1,2,3,4,5},
  },
  [2] = {
   id = 2,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [3] = {
   id = 3,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [4] = {
   id = 4,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [5] = {
   id = 5,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [6] = {
   id = 6,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [7] = {
   id = 7,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [8] = {
   id = 8,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [9] = {
   id = 9,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [10] = {
   id = 10,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [11] = {
   id = 11,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [12] = {
   id = 12,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [13] = {
   id = 13,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [14] = {
   id = 14,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [15] = {
   id = 15,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [16] = {
   id = 16,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [17] = {
   id = 17,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [18] = {
   id = 18,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [19] = {
   id = 19,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [20] = {
   id = 20,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [21] = {
   id = 21,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
  [22] = {
   id = 22,
   cStatements = {},
   statements = {},
   voice = {},
   tableId = -1,
   wordId = {},
   weight = {},
   chaosTableId = -1,
   textId = {},
  },
}
